### ISSUE TITLE
Invalid Manifest file

### ISSUE THREAD

**Issue by Resfelm** [Shuggaloaf/Simple_NPC_Generator#2]
Getting an Invalid Manifest file error when trying to install to Foundry.

**Comment by Shuggaloaf** [comment]
Thanks for reporting this. Looks like I mistakenly copied the wrong manifest link. Yeah, I'm a noob. 

I appreciate the notice and it should be working now. Let me know if not and I will re-open.

**Comment by Resfelm** [comment]
It works fine now and don't worry, making mistakes is the only way to learn. Thanks for the cool module!

**Comment by Shuggaloaf** [comment]
>making mistakes is the only way to learn

I should be a bloody genius by now! ;-) 

And you're quite welcome for the module. It's something I had made for personal use and a few people I play with that also DM really liked it so I thought, why not share? Glad you like it.
