### ISSUE TITLE
Unable to Install on 11

### ISSUE THREAD

**Issue by CaptainMojojojo** [Shuggaloaf/Simple_NPC_Generator#5]
I am getting an error when attempting to install either through module library or direct manifest URL. "Module validation errors: packs: 0: type: may not be undefined."

**Comment by Shuggaloaf** [comment]
Thanks Cap'n! Unfortunately I'm out of town but as soon as I can get to a laptop I will get this fixed. For now I have downgraded compatibility to v8-v10.

Thanks for the heads up!
